### ISSUE TITLE
This is a year old and still has nothing in it

### ISSUE THREAD

**Issue by carbontwelve** [slimphp/Session-Middleware#5]
is this abandoned?

**Comment by bharatpatil** [comment]
Yes, I'm also wating

**Comment by tflight** [comment]
Doesn't sound like this is till in the cards: https://github.com/slimphp/Session-Middleware/issues/4#issuecomment-190292071

**Comment by akrabat** [comment]
There are already a number of PSR-7 session middleware components out there such as:

* https://github.com/Ocramius/PSR7Session
* https://github.com/akrabat/rka-slim-session-middleware
* https://github.com/oscarotero/psr7-middlewares#aurasession

I doubt that Slim will create its own one until there's something unique about it, compared to the other choices.
